name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: ProjectWithMigrations    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dotnetcorewebapp'      # set this to the path to your web app project, defaults to the repository root
  BUILD_CONFIGURATION: 'Release'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{env.BUILD_CONFIGURATION}}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        name: build-artifacts
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
